### ISSUE TITLE
issues with subtitles that are using formatted text, and more

### ISSUE THREAD

**Issue by eximido** [conradRz/readAloudSubtitlesFirefoxExtension#11]
youtube allows some basic formatting like `<b>bold</b>`, `<i>italic</i>` or `<u>underlined</u>` text (and maybe something else i'm not aware of) in the subtitles. this extension however tries to pronounce all the corresponding keywords, which sounds... weird, to say the least. i guess they should be removed from the text before it gets sent to the tts engine.

i've made a small example video to demostrate the issue [here](https://www.youtube.com/watch?v=x9iXsKgM8rc).

also, while preparing the video, i faced even more weird behavior of the extension. at first, by mistake i've selected "English (United States)" as the language of the subtitles, and by some obscure reason it turns out that in that case the extension (both firefox and chrome versions!) is reading the subtitles as if all of them were written on a single line, without any pauses in between. That is at least in English, with Microsoft default TTS.

then i've added another copy of the subtitles to the video and marked them as a plain English (without US mark). and this time the extension reads them properly. however, the very last line gets omitted either way, idk why.

regardless of these issues, i'd like to thank you for creating such an extension. it works pretty fine on videos with simple subtitles.

**Comment by conradRz** [comment]
Well explained/documented. 

Fixed just now.

Will now push updates. Your browser will decide when to update the addon.

**Comment by eximido** [comment]
thank you, reading the text with additional formatting works fine now.

however reading subtitles called "English (United States)" in the video linked above is still bugged for me: it still reads the whole subtitles altogether, completely ignoring their timings. it reads the first line and then proceeds to the next one without stopping, no matter when it actually appears in the video. interesting though, but if i try to turn on a translation to a different language, then it works properly and reads the following lines only when they appear on the screen, not immediately.

subtitles called "English" works properly all the time.
