### ISSUE TITLE
Pausing video to finish reading subtitle?

### ISSUE THREAD

**Issue by bard** [conradRz/readAloudSubtitlesFirefoxExtension#7]
At the moment (and unless I'm doing something wrong), the video keeps playing regardless of whether the TTS engine has finished speaking the current subtitle. Would it be possible to pause the video until the current subtitle has finished being spoken?

E.g. given subtitle `00:30-00:39 Once upon a time there, in a far away kingdom...`, when video is at `00:39`timestamp, if the `end` event from the utterance hasn't been received yet, pause video; when `end` event is received, resume video.

**Comment by conradRz** [comment]
Good point. 

I'll implement your suggestion and then I'll update addon decryptions (and its localizations).

Personally when that happens, I just increase TTS voice speed via the slider in the menu.

**Comment by conradRz** [comment]
Done. 

New versions for the browsers are now published in the "stores" (Firefox, Chrome)

**Comment by bard** [comment]
Well, that was fast! And it works beautifully. Thank you!

**Comment by seszele64** [comment]
how granular are timestamps for the youtube videos?

@conradRz 

do they provide word timestamp of whole chunk
